# docker-compose.yml  ─ root of /opt/node22-stack
services:
  db:
    build: ./db            # or: image: postgres:16  (if you skip db/Dockerfile)
    image: custom-postgres   # local tag to cache future builds
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:                      # ← declares when DB is “healthy”
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      retries: 5
      start_period: 10s

  node:
    build: ./node           # uses node/Dockerfile
    depends_on:             # ← waits for db **and** its health‑check
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://appuser:secretpass@db:5432/appdb
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
